### PR TITLE
Fix anti-patterns

### PR DESCRIPTION
**Pull request by tusharnankani**
#### Describe the changes you've made

This PR fixes antipatterns:
- Remove unused imported modules to optimize performance
- Open files using `with`
  - Opening a file using with statement is preferred as function open implements the context manager protocol that releases the resource when it is outside of the with block. Not doing so requires you to manually release the resource.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Checklist

- [X] My code follows the code style of this project.
- [X] I have performed a self-review of my own code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **[CONTRIBUTING](https://github.com/MLH-Fellowship/alphadoc/blob/main/CONTRIBUTING.md)** document.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by V2dha — APPROVED** [review]

**Comment by tusharnankani** [comment]
Does this come under any DWOC level? @V2dha

**Comment by tusharnankani** [comment]
And what about this @V2dha

**Comment by V2dha** [comment]
> And what about this @V2dha

Sorry forgot about this one! I'll add the labels.

**Comment by V2dha** [comment]
Thank you for your contributions!

**Pull request merged**
